language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

os:
  - linux
  - osx

env:
  - USE_LIBOMP=true
  - USE_LIBOMP=false

addons:
  apt:
    packages:
      - libomp-dev

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update          ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install llvm libomp; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; export PATH=/usr/local/opt/llvm/bin:$PATH; fi

install:
  - pip install -r requirements.txt
  - if [ "$USE_LIBOMP" = true ]; pip setup.py install --omp; fi
  - if [ "$USE_LIBOMP" = false ]; pip setup.py install; fi

script:
  - sh run_all_tests.sh
